### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by iitman66** [michaeldcanady/servicenow-sdk-go#104]
# **❓ Question or Support Request**

## **Describe your question or ask for support.**
Hello

I was using version 1.4.0 and try to migrate to v1.5.0.
Regarding the table iteration, I was using the **NewPageIterator** method from the **PageIterator** class, but this method is now deprecated and should be replaced by NewTablePageIterator[T]

I can then create a **TablePageIterator[TableEntry]** through this method, but there is no Iterate method in **TablePageIterator** class, and I also can't access the **pageIterator** variable as it is not exported.
Therefore, I can't iterate over the table pages

Is there something missing or am I badly using your SDK ?
Thanks for the response

**Comment by michaeldcanady** [comment]
Hey thank you for the question!

If you're trying to use it as `TablePagePageIterator2[T].Iterate(func ( tableEntry T) bool )`, then you're utilizing it correctly. It was my mistake in the implementation - still trying to full understand embedding! I'll open an issue for this!

**Comment by michaeldcanady** [comment]
#105

**Comment by michaeldcanady** [comment]
just released 1.6.0, this should correct this issue! Thank you for the report!
