### ISSUE TITLE
[Question] Provide documentation on updating a record

### ISSUE THREAD

**Issue by nickmaheshwari** [michaeldcanady/servicenow-sdk-go#109]
# **❓ Question or Support Request**

## **Describe your question or ask for support.**
* Hello, using your sdk and overall love it, but I'm having issues figuring our exactly how to update a record. In the [Table README](https://github.com/michaeldcanady/servicenow-sdk-go/blob/main/table-api/Readme.md), you give examples for deleting, retrieving, and creating a record. My use case revolves around retrieving existing records, updating them by potentially adding a task to them, or modifying a task that's already assigned to the record, and/or updating the record's approval / request state. I have no idea how to do any of that based on what I see in the readme. Any help would be much appreciated!

**Comment by nickmaheshwari** [comment]
also curious if you can point me to where all the optional fields of a record are defined. like in the example you provide in your reddit post (https://www.reddit.com/r/golang/comments/1amej3p/introducing_servicenowsdkgo_a_go_sdk_for/?share_id=SZNpq5xlfAfwkv8Dk3zzp&utm_content=1&utm_medium=android_app&utm_name=androidcss&utm_source=share&utm_term=1) you access the record's description with `shortDesc, _ := record.Value("short_description").ToString()` is there a list somewhere of these fields like 'short_description' ?

**Comment by michaeldcanady** [comment]
Hello!
Thank you for your kind words and for using our SDK. I’m glad to hear that you’re finding it useful!

Make sure to only include the fields you want to update.

## Update Record Example

### Example 1

```golang
package main

import (
    tableapi "github.com/michaeldcanady/servicenow-sdk-go/table-api"
    servicenowsdk "github.com/michaeldcanady/servicenow-sdk-go"
)

func main() {
    pathParameters := map[string]string{
        "baseurl": fmt.Sprintf("https://%s.service-now.com/api/now", instance),
        "table":   "incident",
        "sysId":   "{sysid}",
    }

    // Instantiate new TableItemRequestBuilder.
    requestBuilder := tableapi.NewTableItemRequestBuilder(client, pathParameters)

    tableEntry := map[string]string{
        //Fields you wish to update
        "opened_at": "2021-07-22 14:04:59",
    }

    // Call the put2 method, with or without TableItemRequestBuilderPutQueryParameters.
    resp, err := requestBuilder.Put2(tableEntry, nil)
    if err != nil {
        panic(err)
    }
    // Preform operations with your data
}
```

### Example 2

```golang
package main

import (
    tableapi "github.com/michaeldcanady/servicenow-sdk-go/table-api"
    servicenowsdk "github.com/michaeldcanady/servicenow-sdk-go"
)

func main() {
    pathParameters := {
        "baseurl": fmt.Sprintf("https://%s.service-now.com/api/now", instance),
        "table": "incident",
        "sysId": "{sysid}",
    }

    // Instantiate new TableItemRequestBuilder.
    requestBuilder := tableapi.NewTableItemRequestBuilder(client, pathParameters)

    tableEntry := tableapi.NewTableEntry()
    tableEntry.Set("short_description", "I am a short description1")

    // Call the put2 method, with or without TableItemRequestBuilderPutQueryParameters.
    resp, err := requestBuilder.Put2(tableEntry, nil)

    // Preform operations with your data
}
```

## Finding Field Definitions

Regarding the optional fields of a record, these are defined based on the table schema in ServiceNow. To discover all available fields for a particular record, you can indeed use the `Keys()` method on any `TableEntry` object to get a list of all property names.

```golang
// Creating new entry for example but use an existing one
tableEntry := tableapi.NewTableEntry()
tableEntry.Set("short_description", "I am a short description1")

keys := tableEntry.Keys()

fmt.Println(keys)
// Output: [short_description n ...]
```

Additionally you can check the specific table documentation for your instance to find detailed descriptions of each field.
I hope this helps! If you need further assistance, feel free to ask.

**Comment by nickmaheshwari** [comment]
Tysm for the quick reply! This worked perfectly! Would you mind providing an example on how to create a requested item (I believe the table would be sc_req_item) and have that assigned to an existing request, or to assign a request to a group/user? I'm struggling to figure out how to do that. Thanks again!

**Comment by michaeldcanady** [comment]
No problem! I haven't managed requested item's relationships (i.e.: related in the UI).
# Setting Assigned User
For setting the assigned user (assigned_user) you do a put request with either the sys_id or username.

```golang
data := map[string]string{
"assigned_user": "{sys_id/username}"
}
requestBuilder.Put(data, nil)
```

# Setting Assignment Group
For the assignment group (assignment_group) you do a put request with either the group name or sys_id.

```golang
data := map[string]string{
"assignment_group": "{sys_id/group name}"
}
requestBuilder.Put(data, nil)
```

**Comment by nickmaheshwari** [comment]
Thank you so much!
