### ISSUE TITLE
How do you get the results of the nextpage ? 

### ISSUE THREAD

**Issue by lanpar** [michaeldcanady/servicenow-sdk-go#119]
i am able to response, err := requestBuilder.Get(nil) , now do i need to rebuild the requestbuilder again to get the next page and how do dyou do that ?

**Comment by michaeldcanady** [comment]
Hey! Thank you for the question! To iterate over the pages/records that's where you'd use the `tableapi.TablePageIterator[T]`, if working within the table-api specifically.
Here's an example for you:

```golang
iterator, err := tableapi.NewTablePageIterator(response, client)
if err != nil {
    // Handle err
}
iterator.Iterate(func(item){
// if you want to iterate through each result
})

iterator.Next() // if you want the next page of results
```

**Comment by lanpar** [comment]
thanks i also noticed that after 4 pages it failed when pulling incident 

request failed invalid character '}' after object key


not sure if this a known issue this was for version 1.6.1  and going to older or new version get another kind of error 

 unsupported content type: application/json;charset=UTF-8
 
 
 
 anyway perhaps i am doing something wrong

**Comment by lanpar** [comment]
@michaeldcanady - looks like the request failed invalid character '}' after object key - can be avoided with page limit
