### ISSUE TITLE
Table Iteration on Next page ends with "uri cannot be empty"

### ISSUE THREAD

**Issue by iitman66** [michaeldcanady/servicenow-sdk-go#57]
### Issue description
When iterating other pages (table api), the Iterate function call gives error "uri cannot be empty" when accessing the next page.
This error seems to indicate that the UrlTemplate field is empty during the Send of the next link

### Use Case
What problem would this feature solve?

Correct behavior of the Iteration process

### Proposed Solution
During the call of the Next link, as part of the iteration process, the UrlTemplate field should be initialized from the initial request Builder

### Additional Context
Code for reproducing the issue:
```
import (
    "fmt"
    snowcred "github.com/michaeldcanady/servicenow-sdk-go/credentials"
    servicenow "github.com/michaeldcanady/servicenow-sdk-go"
    snowtable "github.com/michaeldcanady/servicenow-sdk-go/table-api"
)

func main() {
    cred := snowcred.NewUsernamePasswordCredential(username, password)
    client := servicenow.NewServiceNowClient(cred, instance)
    fmt.Printf("fetching ServiceNow Computers\n")
    pathParameters := map[string]string{
        "baseurl": client.BaseUrl + "/now",
        "table":   "cmdb_ci_computer",
    }
    requestBuilder := snowtable.NewTableRequestBuilder(client, pathParameters)
    params := &snowtable.TableRequestBuilderGetQueryParameters{
        Limit: 10,
    }
    result, err := requestBuilder.Get(params)
    if err != nil {
        fmt.Printf("unable to GET table %s in ServiceNow: %s\n", "cmdb_ci_computer", err)
        return
    }
    fmt.Printf("fetched devices count: %d\n", len(result.Result))
    pageIterator, err := snowtable.NewPageIterator(*result, client)
    if err != nil {
        fmt.Printf("error on NewPageIterator: %s\n", err)
        return
    }
    cis := []string{}
    iterateErr := pageIterator.Iterate(func(pageItem *snowtable.TableEntry) bool {
        ci, inerr := pageItem.Value("sys_id").ToString()
        if inerr == nil {
            cis = append(cis, ci)
        }
        return true
    })
    if iterateErr != nil {
        fmt.Printf("error on Iterate: %s\n", iterateErr)
        return
    }
    fmt.Printf("Fetched CIs = %d\n", len(cis))
}
```
Results:
```
fetching ServiceNow Computers
fetched devices count: 10
error on Iterate: uri cannot be empty
```

### Checklist
Before submitting this feature request, please make sure you have completed the following:

- [x]  I have searched for similar feature requests in the repository's issue tracker.
- [x]  I have checked the latest version of the Go SDK to see if this feature already exists.
- [x]  I have provided a clear and descriptive title for this feature request.
- [x]  I have provided a detailed description of the feature and its use case.
- [x]  I have provided any relevant additional context or examples.
- [ ]  I have linked any related issues or pull requests.

**Comment by michaeldcanady** [comment]
I'll take a look thank you!
