### ISSUE TITLE
Table Iteration ends after the second iteration as the NextPageLink is empty

### ISSUE THREAD

**Issue by iitman66** [michaeldcanady/servicenow-sdk-go#70]
### Issue description
Opening this issue following resolution of #57
The error message "uri cannot be empty" is no more present.
However, following the second iteration, the links (NextPageLink, PreviousPageLink, FirstPageLink and LastPageLink) are all empty, so the iteration process after the second step

### Use Case
What problem would this feature solve?

Correct behavior of the Iteration process

### Proposed Solution
Fill the links each time the GET calls in the iteration process are performed

### Additional Context
Code for reproducing the issue (got more that 16000 items to retrieve):
```
import (
    "fmt"
    snowcred "github.com/michaeldcanady/servicenow-sdk-go/credentials"
    servicenow "github.com/michaeldcanady/servicenow-sdk-go"
    snowtable "github.com/michaeldcanady/servicenow-sdk-go/table-api"
)

func main() {
    cred := snowcred.NewUsernamePasswordCredential(username, password)
    client := servicenow.NewServiceNowClient(cred, instance)
    fmt.Printf("fetching ServiceNow Computers\n")
    pathParameters := map[string]string{
        "baseurl": client.BaseUrl + "/now",
        "table":   "cmdb_ci_computer",
    }
    requestBuilder := snowtable.NewTableRequestBuilder(client, pathParameters)
    params := &snowtable.TableRequestBuilderGetQueryParameters{
        Limit: 10,
    }
    result, err := requestBuilder.Get(params)
    if err != nil {
        fmt.Printf("unable to GET table %s in ServiceNow: %s\n", "cmdb_ci_computer", err)
        return
    }
    fmt.Printf("fetched devices count: %d\n", len(result.Result))
    pageIterator, err := snowtable.NewPageIterator(*result, client)
    if err != nil {
        fmt.Printf("error on NewPageIterator: %s\n", err)
        return
    }
    cis := []string{}
    iterateErr := pageIterator.Iterate(func(pageItem *snowtable.TableEntry) bool {
        ci, inerr := pageItem.Value("sys_id").ToString()
        if inerr == nil {
            cis = append(cis, ci)
        }
        return true
    })
    if iterateErr != nil {
        fmt.Printf("error on Iterate: %s\n", iterateErr)
        return
    }
    fmt.Printf("Fetched CIs = %d\n", len(cis))
}
```
Results:
```
fetching ServiceNow Computers
fetched devices count: 10
Fetched CIs = 20
```

### Related Issues
Follows #57 

### Checklist
Before submitting this feature request, please make sure you have completed the following:

- [x]  I have searched for similar feature requests in the repository's issue tracker.
- [x]  I have checked the latest version of the Go SDK to see if this feature already exists.
- [x]  I have provided a clear and descriptive title for this feature request.
- [x]  I have provided a detailed description of the feature and its use case.
- [x]  I have provided any relevant additional context or examples.
- [x]  I have linked any related issues or pull requests.

**Comment by michaeldcanady** [comment]
Thank you for your submissions! I have tested it now with a total of 855
![image](https://github.com/michaeldcanady/servicenow-sdk-go/assets/64753032/02e70dc3-e927-46f1-b89e-e56da87dd263)

So with any hope it should be good to go! Thank you for your submissions!
